"""
Django settings for cocinita project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

BASE_DIR = Path(__file__).resolve().parent.parent

# ⚠️ IMPORTANTE: Usar variable de entorno para producción
# En PythonAnywhere, crea un archivo .env o configura las variables en la consola
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-vvp)peja#)ffq_)ib-#r%xuia!1(gq1a*w9q%mtnp#t@fp96p0')

# 🔹 Modo producción: DEBUG = False
DEBUG = True  # ⚠️ IMPORTANTE: Siempre False en producción

# 🔹 Tu dominio en PythonAnywhere
ALLOWED_HOSTS = ['*']  # Solo para desarrollo local

# Apps
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',  
    'rest_framework',
    'rest_framework.authtoken',
    'rest_framework_simplejwt',
    'myapp',
    "corsheaders",
    'envioscocina',
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",  # Para servir archivos estáticos en producción
]

# 🔹 CORS - Configuración más segura para producción
CORS_ALLOWED_ORIGINS = [
    "https://personaldeit.pythonanywhere.com",  # Tu dominio principal
    "https://127.0.0.1:8000",  # ✅ CORREGIDO: agregué los : después de https
    "http://127.0.0.1:8000",   # También agregá HTTP para desarrollo local
    "http://localhost:8000",   # Y localhost
]

# Si necesitas más orígenes (ej: frontend separado), añádelos aquí
# CORS_ALLOW_ALL_ORIGINS = False  # No permitir todos en producción

# Permitir credenciales si usas auth con cookies
CORS_ALLOW_CREDENTIALS = True

ROOT_URLCONF = 'cocinita.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'cocinita.wsgi.application'

# 🔹 BASE DE DATOS - Configuración para MySQL en PythonAnywhere
# Conectando a: personaldeit$default

# Opcional: Si quieres mantener SQLite para desarrollo local
# Puedes comentar MySQL y descomentar esto en local
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    )
}

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# 🔹 Configuración Regional
LANGUAGE_CODE = 'es-ar'  # Español Argentina
TIME_ZONE = 'America/Argentina/Buenos_Aires'
USE_I18N = True
USE_TZ = True

# Formatos de fecha
DATE_FORMAT = 'd/m/Y'
TIME_FORMAT = 'H:i'
DATETIME_FORMAT = 'd/m/Y H:i'

# 🔹 URLs
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/login/'

# 🔹 Archivos estáticos (modo producción)
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# ✅ CORREGIDO: Verificar si la carpeta static existe antes de agregarla
static_dir = BASE_DIR / 'static'
if static_dir.exists():
    STATICFILES_DIRS = [static_dir]
else:
    STATICFILES_DIRS = []  # O comentá esta línea si no existe

# Usar WhiteNoise para servir estáticos en producción
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# 🔹 Archivos media (subidas por usuarios)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# 🔹 Configuración de sesiones (para producción)
SESSION_COOKIE_SECURE = False   # Solo enviar cookies por HTTPS
CSRF_COOKIE_SECURE = False      # CSRF solo por HTTPS
SECURE_SSL_REDIRECT = False     # Redirigir HTTP a HTTPS
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# 🔹 Configuración de seguridad adicional (opcional pero recomendado)
SECURE_BROWSER_XSS_FILTER = False
SECURE_CONTENT_TYPE_NOSNIFF = False
X_FRAME_OPTIONS = 'DENY'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'