# Generated by Django 5.2.4 on 2026-04-23 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviado', 'Enviado'), ('aceptado', 'Aceptado'), ('rechazado', 'Rechazado'), ('entregado', 'Entregado')], default='pendiente', max_length=20)),
                ('fecha_evento', models.DateTimeField(blank=True, help_text='Fecha y hora del evento para el cual se solicita este envío', null=True, verbose_name='Fecha del Evento')),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('fecha_entregado', models.DateTimeField(blank=True, null=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='envios_creados', to=settings.AUTH_USER_MODEL)),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envios_salientes', to='envioscocina.departamento')),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envios_recibidos', to='envioscocina.salon')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del producto')),
                ('cantidad_gramos', models.CharField(blank=True, help_text='Ej: 200g, 10 unidades, 1 bandeja, 8 piezas', max_length=100, null=True, verbose_name='Cantidad o gramos')),
                ('check_1', models.BooleanField(default=False, verbose_name='Check 1')),
                ('es_devolvible', models.BooleanField(default=True)),
                ('detalle', models.TextField(blank=True, null=True, verbose_name='Detalle adicional')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='envioscocina.departamento', verbose_name='Departamento/Isla')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.CharField(blank=True, help_text='Ej: 200g, 5 unidades, 2 bandejas', max_length=100, null=True, verbose_name='Cantidad para este envío')),
                ('check_incluido', models.BooleanField(default=True, verbose_name='Incluido en envío')),
                ('observacion', models.CharField(blank=True, max_length=200, null=True)),
                ('envio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='envioscocina.envio')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='envioscocina.producto')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('departamento', 'Departamento'), ('salon', 'Salón')], max_length=20)),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='envioscocina.departamento')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
                ('salon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='envioscocina.salon')),
            ],
        ),
        migrations.CreateModel(
            name='ConsumoSalon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.CharField(help_text='Ej: 200g, 5 unidades, 2 porciones', max_length=100, verbose_name='Cantidad consumida')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('envio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumos', to='envioscocina.envio')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='envioscocina.producto')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos', to='envioscocina.salon')),
            ],
        ),
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos', to='envioscocina.departamento')),
            ],
            options={
                'verbose_name': 'Tipo de Producto',
                'verbose_name_plural': 'Tipos de Productos',
                'unique_together': {('nombre', 'departamento')},
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='envioscocina.tipoproducto', verbose_name='Tipo'),
        ),
        migrations.CreateModel(
            name='StockSalon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.CharField(default='0', help_text='Ej: 10 unidades, 2kg, 5 bandejas', max_length=100, verbose_name='Stock actual')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='envioscocina.producto')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='envioscocina.salon')),
            ],
            options={
                'unique_together': {('salon', 'producto')},
            },
        ),
    ]
