# Generated by Django 5.2.4 on 2026-04-25 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envioscocina', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='se_puede_reusar',
            field=models.BooleanField(default=False, help_text='True para bebidas, False para comida', verbose_name='Se puede reusar'),
        ),
    ]
