# Generated by Django 6.0.4 on 2026-05-04 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envioscocina', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='es_devolvible',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='se_puede_reusar',
        ),
        migrations.AddField(
            model_name='producto',
            name='comportamiento_stock',
            field=models.CharField(choices=[('stock', 'Impacta stock'), ('aviso', 'Solo aviso de llegada'), ('devuelve', 'Se devuelve')], default='aviso', help_text='Define cómo impacta este producto en el stock del salón', max_length=20, verbose_name='Comportamiento en stock'),
        ),
    ]
