# Generated by Django 6.0.4 on 2026-05-04 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envioscocina', '0002_remove_producto_es_devolvible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleenvio',
            name='cantidad_usada_stock',
            field=models.CharField(blank=True, default='0', max_length=100, null=True, verbose_name='Cantidad usada del stock del salón'),
        ),
        migrations.AddField(
            model_name='envio',
            name='cantidad_invitados',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cantidad de invitados'),
        ),
        migrations.AddField(
            model_name='envio',
            name='plan_evento',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Plan del evento'),
        ),
        migrations.AddField(
            model_name='envio',
            name='tipo_evento',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de evento'),
        ),
    ]
